# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('alias_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'verbose_name_plural': 'games',
                'verbose_name': 'game',
            },
        ),
    ]
