# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:28
from __future__ import unicode_literals

from django.db import migrations


def populate_games(apps, _):
    Game = apps.get_model('games', 'Game')
    GameSession = apps.get_model('stats', 'GameSession')

    games = GameSession.objects.values_list('game', flat=True).distinct()
    games = [Game(name=game) for game in games]
    Game.objects.bulk_create(games)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('stats', '0005_auto_20161006_0018'),
    ]

    operations = [
        migrations.RunPython(populate_games, migrations.RunPython.noop)
    ]
