# Generated by Django 2.2.13 on 2020-08-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
