# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 16:10
from __future__ import unicode_literals

import bot.plugins.reddit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', bot.plugins.reddit.models.LowerCaseCharField(max_length=100, unique=True, verbose_name='command')),
                ('subreddit', bot.plugins.reddit.models.LowerCaseCharField(max_length=50, verbose_name='subreddit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='redditcommand',
            unique_together=set([('command', 'subreddit')]),
        ),
    ]
