# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redditcommand',
            options={'ordering': ['subreddit']},
        ),
        migrations.AddField(
            model_name='redditcommand',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
