# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20160213_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditcommand',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
