# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


def fix(apps, _):
    RedditCommand = apps.get_model('reddit', 'RedditCommand')
    RedditCommand.objects.filter(subreddit='').update(subreddit=models.F('command'))


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_redditcommand_nsfw'),
    ]

    operations = [
        migrations.RunPython(fix, migrations.RunPython.noop)
    ]
