# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50)),
                ('can_admin_bot', models.BooleanField(default=False)),
            ],
        ),
    ]
