# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='discord_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
