# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20160304_1229'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('member_username', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_timestamp', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_authored', to='users.Member')),
                ('mentions', models.ManyToManyField(blank=True, related_name='messages_mentioned_in', to='users.Member')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
