# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmessage',
            name='num_lines',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
