# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_member_is_bot'),
        ('stats', '0002_loggedmessage_num_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255, verbose_name='game')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='stop')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
            },
        ),
    ]
