# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_gamesession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Member'),
        ),
        migrations.AlterField(
            model_name='loggedmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='loggedmessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_authored', to='users.Member'),
        ),
    ]
