# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20161006_0018'),
        ('games', '0002_populate_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='game',
            new_name='_game',
        ),
    ]
