# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='server',
            field=models.CharField(default='90542226181988352', max_length=30, verbose_name='server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggedmessage',
            name='server',
            field=models.CharField(default='90542226181988352', max_length=30, verbose_name='server'),
            preserve_default=False,
        ),
    ]
