# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 18:23
from __future__ import unicode_literals

import bot.plugins.custom_commands.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text="trigger for the command, e.g. 'benis'", max_length=50, validators=[bot.plugins.custom_commands.models.no_prefix_at_beginning], verbose_name='command')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
            },
        ),
        migrations.CreateModel(
            name='CommandAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Text to be replied', verbose_name='action')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_commands.Command')),
            ],
            options={
                'verbose_name': 'command action',
                'verbose_name_plural': 'command actions',
            },
        ),
    ]
