# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('allow_nsfw', models.BooleanField(default=False)),
            ],
        ),
    ]
