# Generated by Django 2.2.13 on 2020-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='discord_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
