# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamenotification',
            unique_together=set([('game_name', 'user')]),
        ),
    ]
