# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_notifications', '0002_auto_20151230_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenotification',
            name='last_notification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
